/obj/machinery/vending/autodrobe
	name = "\improper AutoDrobe"
	desc = "A vending machine for costumes."
	icon_state = "theater"
	icon_deny = "theater-deny"
	panel_type = "panel16"
	req_access = list(ACCESS_THEATRE)
	product_slogans = "Dress for success!;Suited and booted!;It's show time!;Why leave style up to fate? Use AutoDrobe!"
	vend_reply = "Thank you for using AutoDrobe!"
	products = list(
		/obj/item/clothing/suit/chickensuit = 20,
		/obj/item/clothing/head/chicken = 20,
		/obj/item/clothing/under/rank/civilian/clown/blue = 20,
		/obj/item/clothing/under/rank/civilian/clown/green = 20,
		/obj/item/clothing/under/rank/civilian/clown/yellow = 20,
		/obj/item/clothing/under/rank/civilian/clown/orange = 20,
		/obj/item/clothing/under/rank/civilian/clown/purple = 20,
		/obj/item/clothing/under/costume/gladiator = 20,
		/obj/item/clothing/head/helmet/gladiator = 20,
		/obj/item/clothing/under/rank/captain/suit = 20,
		/obj/item/clothing/under/rank/captain/suit/skirt = 20,
		/obj/item/clothing/head/flatcap = 20,
		/obj/item/clothing/suit/toggle/labcoat/mad = 20,
		/obj/item/clothing/shoes/jackboots = 20,
		/obj/item/clothing/under/costume/schoolgirl = 20,
		/obj/item/clothing/under/costume/schoolgirl/red = 20,
		/obj/item/clothing/under/costume/schoolgirl/green = 20,
		/obj/item/clothing/under/costume/schoolgirl/orange = 20,
		/obj/item/clothing/head/kitty = 20,
		/obj/item/clothing/under/dress/skirt = 20,
		/obj/item/clothing/head/beret = 20,
		/obj/item/clothing/accessory/waistcoat = 20,
		/obj/item/clothing/under/suit/black = 20,
		/obj/item/clothing/head/that = 20,
		/obj/item/clothing/under/costume/kilt = 20,
		/obj/item/clothing/head/beret = 3,
		/obj/item/clothing/accessory/waistcoat = 20,
		/obj/item/clothing/glasses/monocle =20,
		/obj/item/clothing/head/bowler = 20,
		/obj/item/cane = 20,
		/obj/item/clothing/under/suit/sl = 20,
		/obj/item/clothing/mask/fakemoustache = 20,
		/obj/item/clothing/suit/bio_suit/plaguedoctorsuit = 20,
		/obj/item/clothing/head/plaguedoctorhat = 20,
		/obj/item/clothing/mask/gas/plaguedoctor = 20,
		/obj/item/clothing/suit/toggle/owlwings = 20,
		/obj/item/clothing/under/costume/owl = 20,
		/obj/item/clothing/mask/gas/owl_mask = 20,
		/obj/item/clothing/suit/toggle/owlwings/griffinwings = 20,
		/obj/item/clothing/under/costume/griffin = 20,
		/obj/item/clothing/shoes/griffin = 20,
		/obj/item/clothing/head/griffin = 20,
		/obj/item/clothing/suit/apron = 20,
		/obj/item/clothing/under/suit/waiter = 20,
		/obj/item/clothing/suit/jacket/miljacket = 20,
		/obj/item/clothing/under/costume/pirate = 20,
		/obj/item/clothing/suit/pirate = 20,
		/obj/item/clothing/head/pirate = 20,
		/obj/item/clothing/head/bandana = 20,
		/obj/item/clothing/head/bandana = 20,
		/obj/item/clothing/under/costume/soviet = 20,
		/obj/item/clothing/head/ushanka = 20,
		/obj/item/clothing/suit/imperium_monk = 20,
		/obj/item/clothing/mask/gas/cyborg = 20,
		/obj/item/clothing/suit/chaplainsuit/holidaypriest = 20,
		/obj/item/clothing/suit/chaplainsuit/whiterobe = 20,
		/obj/item/clothing/head/wizard/marisa/fake = 20,
		/obj/item/clothing/suit/wizrobe/marisa/fake = 20,
		/obj/item/clothing/under/dress/sundress = 20,
		/obj/item/clothing/head/witchwig = 20,
		/obj/item/staff/broom = 20,
		/obj/item/clothing/suit/wizrobe/fake = 20,
		/obj/item/clothing/head/wizard/fake = 20,
		/obj/item/staff = 3,
		/obj/item/clothing/mask/gas/sexyclown = 20,
		/obj/item/clothing/under/rank/civilian/clown/sexy = 20,
		/obj/item/clothing/mask/gas/sexymime = 20,
		/obj/item/clothing/under/rank/civilian/mime/sexy = 20,
		/obj/item/clothing/under/rank/civilian/mime/skirt = 20,
		/obj/item/clothing/mask/animal/rat/bat = 20,
		/obj/item/clothing/mask/animal/rat/bee = 20,
		/obj/item/clothing/mask/animal/rat/bear = 20,
		/obj/item/clothing/mask/animal/rat/raven = 20,
		/obj/item/clothing/mask/animal/rat/jackal = 20,
		/obj/item/clothing/mask/animal/rat/fox = 20,
		/obj/item/clothing/mask/animal/frog = 20,
		/obj/item/clothing/mask/animal/rat/tribal = 20,
		/obj/item/clothing/mask/animal/rat = 20,
		/obj/item/clothing/suit/apron/overalls = 20,
		/obj/item/clothing/head/rabbitears =20,
		/obj/item/clothing/head/sombrero = 20,
		/obj/item/clothing/head/sombrero/green = 20,
		/obj/item/clothing/suit/poncho = 20,
		/obj/item/clothing/suit/poncho/green = 20,
		/obj/item/clothing/suit/poncho/red = 20,
		/obj/item/clothing/under/costume/maid = 20,
		/obj/item/clothing/under/rank/civilian/janitor/maid = 20,
		/obj/item/clothing/glasses/cold=20,
		/obj/item/clothing/glasses/heat=20,
		/obj/item/clothing/suit/whitedress = 20,
		/obj/item/clothing/under/rank/civilian/clown/jester = 20,
		/obj/item/clothing/head/jester = 20,
		/obj/item/clothing/under/costume/villain = 20,
		/obj/item/clothing/shoes/singery = 20,
		/obj/item/clothing/under/costume/singer/yellow = 20,
		/obj/item/clothing/shoes/singerb = 20,
		/obj/item/clothing/under/costume/singer/blue = 20,
		/obj/item/clothing/suit/hooded/carp_costume = 20,
		/obj/item/clothing/suit/hooded/ian_costume = 20,
		/obj/item/clothing/suit/hooded/bee_costume = 20,
		/obj/item/clothing/suit/snowman = 20,
		/obj/item/clothing/head/snowman = 20,
		/obj/item/clothing/mask/joy = 20,
		/obj/item/clothing/head/cueball = 20,
		/obj/item/clothing/under/suit/white_on_white = 20,
		/obj/item/clothing/under/costume/sailor = 20,
		/obj/item/clothing/under/costume/referee = 20,
		/obj/item/clothing/mask/whistle = 20,
		/obj/item/clothing/head/delinquent = 20,
		/obj/item/clothing/head/wig/random = 3,
		/obj/item/clothing/head/shrine_wig = 20,
		/obj/item/clothing/suit/shrine_maiden = 20,
		/obj/item/clothing/suit/changshan_red = 20,
		/obj/item/clothing/suit/changshan_blue = 20,
		/obj/item/clothing/suit/cheongsam_red = 20,
		/obj/item/clothing/suit/cheongsam_blue = 20,
		/obj/item/gohei = 20
	)
	contraband = list(
		/obj/item/clothing/suit/judgerobe = 20,
		/obj/item/clothing/head/powdered_wig = 20,
		/obj/item/gun/magic/wand/nothing = 2,
		/obj/item/clothing/glasses/sunglasses/garb = 2,
		/obj/item/clothing/glasses/blindfold = 20,
		/obj/item/clothing/mask/muzzle = 2
	)
	premium = list(
		/obj/item/clothing/suit/pirate/captain = 2,
		/obj/item/clothing/head/pirate/captain = 2,
		/obj/item/clothing/under/rank/civilian/clown/rainbow = 20,
		/obj/item/clothing/head/helmet/roman/fake = 20,
		/obj/item/clothing/head/helmet/roman/legionnaire/fake = 20,
		/obj/item/clothing/under/costume/roman = 20,
		/obj/item/clothing/shoes/roman = 20,
		/obj/item/shield/riot/roman/fake = 20,
		/obj/item/clothing/suit/chaplainsuit/clownpriest = 20,
		/obj/item/clothing/head/clownmitre = 20,
		/obj/item/skub = 20,
		/obj/item/clothing/suit/hooded/mysticrobe = 20,
		/obj/item/clothing/under/dress/wedding_dress = 20,
		/obj/item/clothing/under/suit/tuxedo = 20,
		/obj/item/clothing/head/weddingveil = 20,
		/obj/item/storage/belt/cummerbund = 20
	)
	refill_canister = /obj/item/vending_refill/autodrobe
	default_price = PAYCHECK_ASSISTANT * 0.8 //Default of 40.
	extra_price = PAYCHECK_HARD
	payment_department = ACCOUNT_SRV
	light_mask="theater-light-mask"

/obj/machinery/vending/autodrobe/canLoadItem(obj/item/I,mob/user)
	return (I.type in products)

/obj/machinery/vending/autodrobe/all_access
	desc = "A vending machine for costumes. This model appears to have no access restrictions."
	req_access = null

/obj/item/vending_refill/autodrobe
	machine_name = "AutoDrobe"
	icon_state = "refill_costume"
